# Generated by Django 3.1.2 on 2020-10-13 16:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('prices', models.CharField(max_length=200)),
                ('facebook', models.CharField(max_length=100)),
                ('twitter', models.CharField(max_length=100)),
                ('is_sponsered', models.BooleanField(default=False)),
                ('submission_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
