# Generated by Django 3.1.2 on 2020-10-14 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0003_startup_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='published',
            field=models.BooleanField(blank=True),
        ),
    ]
