# Generated by Django 3.1.2 on 2020-10-14 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0006_auto_20201014_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='is_sponsered',
            field=models.BooleanField(default=True),
        ),
    ]
