# Generated by Django 3.1.2 on 2020-10-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0007_auto_20201014_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='is_sponsered',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
