# Generated by Django 3.1.2 on 2020-10-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0008_auto_20201016_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='image',
            field=models.ImageField(upload_to='upload/'),
        ),
    ]
