# Generated by Django 3.1.2 on 2020-10-21 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0011_auto_20201018_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
