# Generated by Django 3.1.2 on 2020-10-13 16:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('icon', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('experience', models.CharField(max_length=200)),
                ('job_type', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('job_link', models.BooleanField(default=False)),
                ('submission_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
