# Generated by Django 3.1.2 on 2020-10-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joblist', '0002_auto_20201013_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblist',
            name='published',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
