# Generated by Django 3.1.2 on 2020-10-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joblist', '0008_auto_20201017_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblist',
            name='icon',
            field=models.ImageField(upload_to='JobList'),
        ),
    ]
