# Generated by Django 3.1.2 on 2020-10-12 13:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('user_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('confirm_password', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('prices', models.CharField(max_length=200)),
                ('facebook', models.CharField(max_length=100)),
                ('twitter', models.CharField(max_length=100)),
                ('is_sponsered', models.BooleanField(default=False)),
                ('submission_date', models.DateTimeField(default=datetime.datetime.now)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='listings.contact')),
            ],
        ),
        migrations.CreateModel(
            name='JobList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('experience', models.CharField(max_length=200)),
                ('job_type', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('job_link', models.BooleanField(default=False)),
                ('submission_date', models.DateTimeField(default=datetime.datetime.now)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='listings.contact')),
            ],
        ),
    ]
