# Generated by Django 3.1.2 on 2020-10-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20201012_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblist',
            name='icon',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d'),
        ),
    ]
