# Generated by Django 3.1.2 on 2020-10-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_joblist_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblist',
            name='company_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
