# Generated by Django 3.1.2 on 2020-10-13 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_joblist_company_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobList',
        ),
        migrations.DeleteModel(
            name='Startup',
        ),
    ]
